cache_type: q8_0
ctx: '262144'
host: 0.0.0.0
mmproj_path: F:/GGUF_models/unsloth/gemma-4-E2B-it-GGUF/mmproj-gemma-4-E2B-it-F16.gguf
model_path: F:/GGUF_models/unsloth/gemma-4-E2B-it-GGUF/gemma-4-E2B-it-UD-Q4_K_XL.gguf
ngl: all
port: '8080'
reasoning: 'off'
server_path: D:/Program Files/llama/llama-server.exe
ts_ratio: '28'
